[toolchain]

[features]
resolution = true
skip-lint = false

[programs.devnet]
pirate_academy = "9pHeiuDFexs5HQSmsNbzxhYR1mWW223oeNwFEsz5XWiW"

[registry]
url = "https://api.apr.dev"

[provider]
cluster = "devnet"
wallet = "~/.config/solana/id.json"

[scripts]
test = "cargo test"
